backend:
  replicaCount: 1

  image:
    repository: shopping-backend
    tag: latest
    pullPolicy: Never

  service:
    port: 5000

  config:
    dbName: shopping
    port: "5000"

  secret:
    dbUser: root
    dbPassword: root

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 500m
      memory: 512Mi

  probes:
    liveness:
      path: /health
      initialDelaySeconds: 10
      periodSeconds: 10

    readiness:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5

frontend:
  replicaCount: 1

  image:
    repository: shopping-frontend
    tag: latest
    pullPolicy: Never

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      cpu: 50m
      memory: 64Mi

    limits:
      cpu: 250m
      memory: 128Mi

  probes:
    liveness:
      path: /
      initialDelaySeconds: 5
      periodSeconds: 10

    readiness:
      path: /
      initialDelaySeconds: 3
      periodSeconds: 5

mysql:
  replicaCount: 1

  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3306

  auth:
    database: shopping
    username: root
    password: root

  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi

    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  host: shopping.local
