apiVersion: v1
kind: Secret

metadata:
  name: {{ include "shopping-app.fullname" . }}-backend-secret

  labels:
    {{- include "shopping-app.labels" . | nindent 4 }}

type: Opaque

stringData:
  DB_USER: {{ .Values.backend.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.backend.secret.dbPassword | quote }}
