apiVersion: v1
kind: Service

metadata:
  name: {{ include "shopping-app.fullname" . }}-backend-service

  labels:
    {{- include "shopping-app.labels" . | nindent 4 }}

spec:
  type: ClusterIP

  selector:
    app: {{ include "shopping-app.fullname" . }}-backend

  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
    protocol: TCP
