apiVersion: v1
kind: Service

metadata:
  name: {{ include "shopping-app.fullname" . }}-frontend-service

  labels:
    {{- include "shopping-app.labels" . | nindent 4 }}

spec:
  type: {{ .Values.frontend.service.type }}

  selector:
    app: {{ include "shopping-app.fullname" . }}-frontend

  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
    protocol: TCP
